#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Tue Feb 21 22:17:10 CST 2017
# module: mvn
# Action: deploy
# Simplify third party artifact deploy, e.g.: hi mvn install jar gid=com.oracle aid=ojdbc14 ver=10.2.0.5.0
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/clap"
source "${HI_CLI_HOME}/bin/logging"
###############################################################################
function run() {
  cli="mvn deploy -Dbuild=dev"

  if [ "${jar}" != "" ]; then
    if [ "${jar}" == "jar" ]; then
      if [ "${aid}" != "" ]; then
        jar=${aid}.jar
        if [ ! -f ${jar} ];
        then
          jar=${aid}-${ver}.jar
        fi
      else
        jar=
      fi
    fi

    if [ "${jar}" != "" ]; then
      cli="mvn deploy:deploy-file -DgroupId=${gid} -DartifactId=${aid} -Dversion=${ver} -Dpackaging=jar -Dfile=${jar} -Durl=${MAVEN_URL}"
    fi
  fi

  ${cli}

  result=$?

  eval $1="$result"
}

###############################################################################


