#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Wed Mar 22 20:58:31 CST 2017
# Module: mp
# Action: generate
###############################################################################


DB_NAME=mybatis_plus
DB_HOST=172.16.5.90
DB_URL=jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?characterEncoding=utf8
DB_USER=root
DB_PASSWORD=${password}
DB_DRIVER=com.mysql.jdbc.Driver
GROUP_ID=cn.vpclub.moses
PACKAGE=mpdemo
AUTHOR=rc
TARGET=${PWD}/src/main/java