#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Wed Mar 22 20:58:31 CST 2017
# module: mp
# Action: generate
###############################################################################

source ${HI_CLI_HOME}/bin/colors
source ${HI_CLI_HOME}/bin/clap
source ${HI_CLI_HOME}/bin/logging
###############################################################################
function run() {

  gid=${GROUP_ID}

  
  if [ -f pom.xml ]; 
  then
    cli=$(cat <<-EOF
java -cp lib/commons-lang3-3.4.jar:lib/slf4j-api-1.7.12.jar:lib/velocity-1.7.jar:lib/mybatis-plus-2.0.2.jar:lib/mp-generator.jar:lib/mybatis-3.4.2.jar:lib/mysql-connector-java-5.1.39.jar:lib/commons-collections-3.2.1.jar:lib/commons-lang-2.4.jar cn.vpclub.moses.mp.generator.MpGenerator tablePrefixs=null&password=${DB_PASSWORD}&packageParent=${GROUP_ID}&packageModuleName=${PACKAGE}&author=${AUTHOR}&driverName=${DB_DRIVER}&url=${DB_URL}&outdir=${TARGET}&username=${DB_USER}
EOF
)
    pushd ${module_dir} > /dev/null
    ${cli}
    mvn clean install -Dmaven.skip.test=true
    ${cli}&generationType=${GEN_TYPE}
    result=$?
    popd
  else
    log_warn "Please run this command in maven project"
    result=1
  fi
  
  eval  $1="\${result}"
  eval  $2="\${cli}"
}

###############################################################################


