#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Tue Feb 21 20:19:52 CST 2017
# module: volume
# Action: create
###############################################################################

source ${HI_CLI_HOME}/bin/colors
source ${HI_CLI_HOME}/bin/clap
source ${HI_CLI_HOME}/bin/logging
source ${HI_CLI_HOME}/bin/utils
source ${HI_CLI_HOME}/modules/heketi/init
###############################################################################

function run() {
  
  log_debug "module_dir: ${module_dir}, command: ${module_command}"
  src=$(cat ${module_dir}/endpoint.json)
  
  parse_json result "${src}" metadata name
  log_debug "${result}"
  
  cli="echo 'test parse json'"

  result=$?

  eval  $1="\${result}"
  eval  $2="\${cli}"
}

###############################################################################



